In [1]:
from keras.datasets import mnist
import numpy as np

Using TensorFlow backend.
/Users/aaronwayne/miniconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
print(x_train.shape)
print(x_train[0,:,:])

# standardize
new_x_train = x_train / 255

print(new_x_train.shape)

reshaped_x_train = np.reshape(new_x_train, (60000, 28*28))

(60000, 28, 28)
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 25

In [4]:
print(y_train.shape)

new_y_train = np.zeros((60000,10))
for (i, value) in enumerate(y_train):
    new_y_train[i, value] = 1

(60000,)


In [5]:
# weights_1 = np.random.normal(size=(28*28, 128), scale=1/np.sqrt(28*28))
# biases_1 = np.zeros((1, 128))

In [6]:
#def sigmoid(z):
#    return 1/(1+np.exp(-z))

In [7]:
#def pre_activations(X, W, b):
#    return np.dot(X,W) + b

In [8]:
#def activations(X, W, b):
#    return sigmoid(pre_activations(X, W, b))

In [9]:
#weights_2 = np.random.normal(size=(128, 10), scale=1/np.sqrt(128))
#biases_2 = np.zeros((1, 10))

In [10]:
#def soft_max(X, W, b):
#    z = pre_activations(X, W, b)
#    expz = np.exp(z)
#    sums = np.sum(expz, axis=0)
#    return expz / sums

In [11]:
#def forward_propogate(X):
#    hidden_1 = activations(X, weights_1, biases_1)
#    return soft_max(hidden_1, weights_2, biases_2)

In [15]:
class DenseLayer:

    def __init__(self, input_length, output_length):
        self.in_len = input_length
        self.out_len = output_length
        self.weights = np.random.normal(size=(self.in_len, self.out_len), scale=1/np.sqrt(self.out_len))
        self.biases = np.zeros((1, self.out_len))

    def soft_max(self, X):
        pre = self.pre_activations(X)
        exp_pre = np.exp(pre)
        #sums = np.sum(exp_pre, axis=0)
        sums = np.dot(exp_pre, np.ones((10,1)))
        return exp_pre / sums

    def activations(self, X):
        pre = self.pre_activations(X)
        return self.__class__.sigmoid(pre)

    def pre_activations(self, X):
        return np.dot(X, self.weights) + self.biases

    @staticmethod
    def sigmoid(z):
        return 1 / (1 + np.exp(-z))


In [16]:
class Network:

    def __init__(self, data):
        self.layers = []
        # add line to reshape if it isn't correct
        self.data = data

    def add_layer(self, output_length):
        num_layers = len(self.layers)
        in_len = self.layers[num_layers - 1].out_len if num_layers > 0 else self.data.shape[1]
        self.layers.append(DenseLayer(in_len, output_length))

    def forward_propogate(self):
        result = self.data
        for (i, layer) in enumerate(self.layers):
            if (i == len(self.layers) - 1):
                return layer.soft_max(result)
            else:
                result = layer.activations(result)

In [17]:
net = Network(reshaped_x_train)
net.add_layer(128)
net.add_layer(128)
net.add_layer(128)
net.add_layer(10)
print(net.forward_propogate())
print(sum(net.forward_propogate()[0]))

[[0.18669996 0.02264571 0.00171229 ... 0.05002698 0.19734373 0.04697053]
 [0.17686762 0.02369618 0.00174104 ... 0.04891883 0.2076648  0.0459914 ]
 [0.17575016 0.02204357 0.0017631  ... 0.04622285 0.19061613 0.04892695]
 ...
 [0.19783043 0.02355495 0.00169083 ... 0.05064176 0.19370544 0.0466007 ]
 [0.18917529 0.02327006 0.0017239  ... 0.04851646 0.19079796 0.04639608]
 [0.1824049  0.02238624 0.00170184 ... 0.04664266 0.1904163  0.04756369]]
1.0
